openapi: 3.0.3
info:
  description: This document describes the UBKG API
  title: UBKG API
  version: 1.2.0
servers:
- url: https://ontology.api.hubmapconsortium.org/
paths:
  /assaytype/{name}:
    get:
      operationId: assaytype_name_get
      parameters:
      - description: AssayType name
        explode: false
        in: path
        name: name
        required: true
        schema:
          example: bulk-RNA
          type: string
        style: simple
      - description: Filter to indicate application context
        explode: true
        in: query
        name: application_context
        required: false
        schema:
          default: HUBMAP
          enum:
          - HUBMAP
          - SENNET
          - hubmap
          - sennet
          - HuBMAP
          - SenNet
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              example:
                name: bulk-RNA
                primary: true
                description: Bulk RNA-seq
                vitessce-hints:
                - pyramid
                - anndata
                contains-pii: true
                vis-only: true
              schema:
                $ref: '#/components/schemas/AssayTypePropertyInfo'
          description: A JSON array of the assay type name
      summary: "Returns information on a set of HuBMAP or SenNet dataset types, with\
        \ options to filter the list to those with specific property values. Filters\
        \ are additive (i.e., boolean AND)"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /codes/{code_id}/codes:
    get:
      operationId: codes_code_id_codes_get
      parameters:
      - description: The code identifier
        explode: false
        in: path
        name: code_id
        required: true
        schema:
          example: SNOMEDCT_US 254837009
          type: string
        style: simple
      - description: One or more sources (SABs) to return
        explode: true
        in: query
        name: sab
        required: false
        schema:
          default: []
          items:
            example: "NCI,MDR"
            type: string
          type: array
          uniqueItems: true
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CodesCodesObj'
                type: array
          description: A JSON array of dictionaries
      summary: "Returns a list of code_ids {Concept, Code, SAB} that code the same\
        \ concept(s) as the code_id, optionally restricted to source (SAB)"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /codes/{code_id}/concepts:
    get:
      operationId: codes_code_id_concepts_get
      parameters:
      - description: The code identifier
        explode: false
        in: path
        name: code_id
        required: true
        schema:
          example: SNOMEDCT_US 254837009
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConceptDetail'
                type: array
          description: A JSON array of dictionaries
      summary: "Returns a list of concepts {Concept, Prefterm} that the code_id codes"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/expand:
    post:
      operationId: concepts_expand_post
      requestBody:
        content:
          application/json:
            example:
              query_concept_id: C2720507
              sab:
              - SNOMEDCT_US
              - HGNC
              rel:
              - isa
              - isa
              depth: 2
            schema:
              $ref: '#/components/schemas/ConceptSabRelDepth'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConceptPrefterm'
                type: array
          description: "Return all {concept, prefterm}"
      summary: "Returns a unique list of concepts (Concept, Preferred Term) on all\
        \ paths including starting concept (query_concept_id) restricted by list of\
        \ relationship types (rel), list of relationship sources (sab), and depth\
        \ of travel."
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/paths:
    post:
      operationId: concepts_path_post
      requestBody:
        content:
          application/json:
            example:
              query_concept_id: C2720507
              sab:
              - SNOMEDCT_US
              - HGNC
              rel:
              - isa
              - isa
            schema:
              $ref: '#/components/schemas/ConceptSabRel'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PathItemConceptRelationshipSabPrefterm'
                type: array
          description: Return all paths of the relationship pattern specified within
            the selected sources
      summary: Return all paths of the relationship pattern specified within the selected
        sources
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/shortestpaths:
    post:
      operationId: concepts_shortestpaths_post
      requestBody:
        content:
          application/json:
            example:
              query_concept_id: C2720507
              target_concept_id: C1272753
              sab:
              - SNOMEDCT_US
              - HGNC
              rel:
              - isa
              - part_of
            schema:
              $ref: '#/components/schemas/QconceptTconceptSabRel'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PathItemConceptRelationshipSabPrefterm'
                type: array
          description: Return all paths of the relationship pattern specified within
            the selected sources
      summary: Return all paths of the relationship pattern specified within the selected
        sources
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/trees:
    post:
      operationId: concepts_trees_post
      requestBody:
        content:
          application/json:
            example:
              query_concept_id: C2720507
              sab:
              - SNOMEDCT_US
              - HGNC
              rel:
              - isa
              - isa
              depth: 2
            schema:
              $ref: '#/components/schemas/ConceptSabRelDepth'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/PathItemConceptRelationshipSabPrefterm'
                type: array
          description: Return all paths of the relationship pattern specified within
            the selected sources
      summary: Return all paths of the relationship pattern specified within the selected
        sources
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/codes:
    get:
      operationId: concepts_concept_id_codes_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0678222
          type: string
        style: simple
      - description: One or more sources (SABs) to return
        explode: true
        in: query
        name: sab
        required: false
        schema:
          default: []
          items:
            example: "MEDLINEPLUS,MSH,MEDCIN"
            type: string
          type: array
          uniqueItems: true
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  example: CHV 0000052645
                  type: string
                type: array
          description: A JSON array of code_id(s) that code the concept
      summary: Returns a distinct list of code_id(s) that code the concept
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/concepts:
    get:
      operationId: concepts_concept_id_concepts_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0006142
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SabRelationshipConceptTerm'
                type: array
          description: "A JSON array of {Sab, Relationship, Concept, Prefterm} dictionaries"
      summary: "Returns a list of concepts {Sab, Relationship, Concept, Prefterm}\
        \ related to the concept"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/definitions:
    get:
      operationId: concepts_concept_id_definitions_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0006142
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SabDefinition'
                type: array
          description: "A JSON array of {Sab, Definition} dictionaries"
      summary: "Returns a list of definitions {Sab, Definition} of the concept"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /concepts/{concept_id}/semantics:
    get:
      operationId: concepts_concept_id_semantics_get
      parameters:
      - description: The concept identifier
        explode: false
        in: path
        name: concept_id
        required: true
        schema:
          example: C0304055
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/StyTuiStn'
                type: array
          description: "A JSON array of {Sty, Tui, Stn} dictionaries"
      summary: "Returns a list of semantic_types {Sty, Tui, Stn} of the concept"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /datasets:
    get:
      operationId: dataset_get
      parameters:
      - description: Required filter to indicate application context.
        explode: true
        in: query
        name: application_context
        required: true
        schema:
          enum:
          - HUBMAP
          - SENNET
          - hubmap
          - sennet
          - HuBMAP
          - SenNet
          type: string
        style: form
      - description: Optional filter for data_type
        explode: true
        in: query
        name: data_type
        required: false
        schema:
          example: AF
          type: string
        style: form
      - description: Optional filter for display name. Use URL-encoding (space = %20).
        explode: true
        in: query
        name: description
        required: false
        schema:
          example: Autofluorescence%20Microscopy
          type: string
        style: form
      - description: "Optional filter for a single element in the alt-names list--i.e.,\
          \ return datasets for which alt-names includes a value that matches the\
          \ parameter. Although the field is named 'alt-names', the parameter uses\
          \ 'alt_name'. Use URL-encoding (space = %20)"
        explode: true
        in: query
        name: alt_name
        required: false
        schema:
          example: Light%20Sheet
          type: string
        style: form
      - description: Optional filter to filter to primary (true) or derived (false)
          assay.
        explode: true
        in: query
        name: primary
        required: false
        schema:
          enum:
          - "true"
          - "false"
          type: string
        style: form
      - description: "Optional filter for whether the dataset contains Patient Identifying\
          \ Information (PII). Although the field is named 'contains-pii', use 'contains_pii'\
          \ as an argument."
        explode: true
        in: query
        name: contains_pii
        required: false
        schema:
          enum:
          - "true"
          - "false"
          type: string
        style: form
      - description: "Optional filter for whether datasets are visualization only\
          \ (true). Although the field is named 'vis-only', use 'vis_only' as an argument."
        explode: true
        in: query
        name: vis_only
        required: false
        schema:
          enum:
          - "true"
          - "false"
          type: string
        style: form
      - description: "Optional filter for a single element in the vitessce_hint list--i.e.,\
          \ return datasets for which vitessce_hints includes a value that matches\
          \ the parameter. Although the field is named 'vitessce-hints', use 'vitessce_hint'\
          \ as an argument."
        explode: true
        in: query
        name: vitessce_hint
        required: false
        schema:
          enum:
          - pyramid
          - anndata
          - is_image
          - is_tiled
          - is_sc
          - rna
          - atac
          - sprm
          - codex
          - maldi
          type: string
        style: form
      - description: Optional filter to identify the dataset provider - IEC (iec)  or
          external (lab)
        explode: true
        in: query
        name: dataset_provider
        required: false
        schema:
          enum:
          - iec
          - IEC
          - external
          - External
          - lab
          - Lab
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/DatasetPropertyInfo'
                type: array
          description: "A JSON array of dataset types with properties, optionally\
            \ filtered by parameters"
      summary: "Returns information on a set of HuBMAP or SenNet dataset types, with\
        \ options to filter the list to those with specific property values. Filters\
        \ are additive (i.e., boolean AND)"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /semantics/{semantic_id}/semantics:
    get:
      operationId: semantics_semantic_id_semantics_get
      parameters:
      - description: The semantic identifier
        explode: false
        in: path
        name: semantic_id
        required: true
        schema:
          example: Physical Object
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/QQST'
                type: array
          description: "A JSON array of {queryTUI, querySTN ,semantic, TUI_STN} dictionaries"
      summary: "Returns a list of semantic_types {queryTUI, querySTN ,semantic, TUI_STN}\
        \ of the semantic type"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /terms/{term_id}/codes:
    get:
      operationId: terms_term_id_codes_get
      parameters:
      - description: The term identifier
        explode: false
        in: path
        name: term_id
        required: true
        schema:
          example: Breast cancer
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/TermtypeCode'
                type: array
          description: "A JSON array of {TermType, Code} dictionaries"
      summary: "Returns a list of codes {TermType, Code} of the text string"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /terms/{term_id}/concepts:
    get:
      operationId: terms_term_id_concepts_get
      parameters:
      - description: The term identifier
        explode: false
        in: path
        name: term_id
        required: true
        schema:
          example: Breast cancer
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  example: C0794811
                  type: string
                type: array
          description: A JSON array of concepts associated with the term
      summary: Returns a list of concepts associated with the text string
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /terms/{term_id}/concepts/terms:
    get:
      operationId: terms_term_id_concepts_terms_get
      parameters:
      - description: The term identifier
        explode: false
        in: path
        name: term_id
        required: true
        schema:
          example: Breast cancer
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ConceptTerm'
                type: array
          description: "A JSON array of {Concept, Term} dictionaries"
      summary: "Returns an expanded list of concept(s) and preferred term(s) {Concept,\
        \ Term} from an exact text match"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /tui/{tui_id}/semantics:
    get:
      operationId: tui_tui_id_semantics_get
      parameters:
      - description: The TUI identifier
        explode: false
        in: path
        name: tui_id
        required: true
        schema:
          example: T200
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SemanticStn'
                type: array
          description: "A JSON array of {semantic, STN} dictionaries"
      summary: "Returns a list of symantic_types {semantic, STN} of the type unique\
        \ id (tui)"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /valueset:
    get:
      operationId: valueset_get
      parameters:
      - description: the SAB of the parent concept
        explode: true
        in: query
        name: parent_sab
        required: true
        schema:
          example: HUBMAP
          type: string
        style: form
      - description: the code of the parent concept in the SAB (local ontology)
        explode: true
        in: query
        name: parent_code
        required: true
        schema:
          example: C000530
          type: string
        style: form
      - description: "the list of SABs for child concepts, in order of preference\
          \ (in case of parent concepts with cross-references)"
        explode: true
        in: query
        name: child_sabs
        required: true
        schema:
          default: []
          items:
            example: "HUSAT,SNOMEDCT_US"
            type: string
          type: array
          uniqueItems: true
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SabCodeTerm'
                type: array
          description: A JSON array of preferred terms for child codes that have an
            isa relationship with the parent code
      summary: Returns a valueset of concepts that are children (have as isa relationship)
        of another concept.
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    CodesCodesObj:
      example:
        code: CCS 2.5
        SAB: CCF
        concept: C0006142
      properties:
        concept:
          example: C0006142
          title: concept
          type: string
        code:
          example: CCS 2.5
          title: code
          type: string
        SAB:
          example: CCF
          title: SAB
          type: string
      title: CodesCodesObj
      type: object
    ConceptDetail:
      example:
        concept: C0006142
        prefterm: Malignant neoplasm of breast
      properties:
        concept:
          example: C0006142
          title: concept
          type: string
        prefterm:
          example: Malignant neoplasm of breast
          title: prefterm
          type: string
      title: ConceptDetail
      type: object
    ConceptSabRel:
      example:
        sab:
        - SNOMEDCT_US
        - HGNC
        rel:
        - isa
        - isa
        query_concept_id: C2720507
      properties:
        query_concept_id:
          example: C2720507
          title: query_concept_id
          type: string
        sab:
          example:
          - SNOMEDCT_US
          - HGNC
          items:
            type: string
          title: sab
          type: array
        rel:
          example:
          - isa
          - isa
          items:
            type: string
          title: rel
          type: array
      title: ConceptSabRel
      type: object
    ConceptSabRelDepth:
      example:
        depth: 2
        sab:
        - SNOMEDCT_US
        - HGNC
        rel:
        - isa
        - isa
        query_concept_id: C2720507
      properties:
        query_concept_id:
          example: C2720507
          title: query_concept_id
          type: string
        sab:
          example:
          - SNOMEDCT_US
          - HGNC
          items:
            type: string
          title: sab
          type: array
        rel:
          example:
          - isa
          - isa
          items:
            type: string
          title: rel
          type: array
        depth:
          example: 2
          title: depth
          type: integer
      title: ConceptSabRelDepth
      type: object
    ConceptPrefterm:
      example:
        concept: C0006826
        prefterm: Malignant Neoplasms
      properties:
        concept:
          example: C0006826
          title: concept
          type: string
        prefterm:
          example: Malignant Neoplasms
          title: prefterm
          type: string
      title: ConceptPrefterm
      type: object
    ConceptTerm:
      example:
        concept: C0006826
        term: LNC LA14283-8
      properties:
        concept:
          example: C0006826
          title: concept
          type: string
        term:
          example: LNC LA14283-8
          title: term
          type: string
      title: ConceptTerm
      type: object
    PathItemConceptRelationshipSabPrefterm:
      example:
        path: path
        item: item
        sab: ICD10AM
        concept: C0006826
        prefterm: Malignant Neoplasms
        relationship: CHD
      properties:
        path:
          title: path
          type: string
        item:
          title: item
          type: string
        concept:
          example: C0006826
          title: concept
          type: string
        relationship:
          example: CHD
          title: relationship
          type: string
        sab:
          example: ICD10AM
          title: sab
          type: string
        prefterm:
          example: Malignant Neoplasms
          title: prefterm
          type: string
      title: PathItemConceptRelationshipSabPrefterm
      type: object
    QconceptTconceptSabRel:
      example:
        target_concept_id: C1272753
        sab:
        - SNOMEDCT_US
        - HGNC
        rel:
        - isa
        - part_of
        query_concept_id: C2720507
      properties:
        query_concept_id:
          example: C2720507
          title: query_concept_id
          type: string
        target_concept_id:
          example: C1272753
          title: target_concept_id
          type: string
        sab:
          example:
          - SNOMEDCT_US
          - HGNC
          items:
            type: string
          title: sab
          type: array
        rel:
          example:
          - isa
          - part_of
          items:
            type: string
          title: rel
          type: array
      title: QconceptTconceptSabRel
      type: object
    QQST:
      example:
        semantic: Entity
        querySTN: A1
        queryTUI: T072
        TUI: T071
        STN: A
      properties:
        queryTUI:
          example: T072
          title: queryTUI
          type: string
        querySTN:
          example: A1
          title: querySTN
          type: string
        semantic:
          example: Entity
          title: semantic
          type: string
        TUI:
          example: T071
          title: TUI
          type: string
        STN:
          example: A
          title: STN
          type: string
      title: QQST
      type: object
    SabDefinition:
      example:
        sab: NCI
        definition: A primary or metastatic malignant neoplasm involving the breast.
          The vast majority of cases are carcinomas arising from the breast parenchyma
          or the nipple. Malignant breast neoplasms occur more frequently in females
          than in males.
      properties:
        sab:
          example: NCI
          title: sab
          type: string
        definition:
          example: A primary or metastatic malignant neoplasm involving the breast.
            The vast majority of cases are carcinomas arising from the breast parenchyma
            or the nipple. Malignant breast neoplasms occur more frequently in females
            than in males.
          title: definition
          type: string
      title: SabDefinition
      type: object
    SabRelationshipConceptTerm:
      example:
        sab: ICD10AM
        concept: C0006826
        prefterm: Malignant Neoplasms
        relationship: CHD
      properties:
        sab:
          example: ICD10AM
          title: sab
          type: string
        relationship:
          example: CHD
          title: relationship
          type: string
        concept:
          example: C0006826
          title: concept
          type: string
        prefterm:
          example: Malignant Neoplasms
          title: prefterm
          type: string
      title: SabRelationshipConceptTerm
      type: object
    SemanticStn:
      example:
        semantic: Entity
        STN: A
      properties:
        semantic:
          example: Entity
          title: semantic
          type: string
        STN:
          example: A
          title: STN
          type: string
      title: SemanticStn
      type: object
    StyTuiStn:
      example:
        sty: Organic Chemical
        tui: T109
        stn: A1.4.1.2.1
      properties:
        sty:
          example: Organic Chemical
          title: sty
          type: string
        tui:
          example: T109
          title: tui
          type: string
        stn:
          example: A1.4.1.2.1
          title: stn
          type: string
      title: StyTuiStn
      type: object
    TermtypeCode:
      example:
        code: LNC LA14283-8
        termtype: LA
      properties:
        termtype:
          example: LA
          title: termtype
          type: string
        code:
          example: LNC LA14283-8
          title: code
          type: string
      title: TermtypeCode
      type: object
    SabCodeTerm:
      example:
        code: C16853
        sab: NCI
        term: Microscopy
      properties:
        sab:
          example: NCI
          title: sab
          type: string
        code:
          example: C16853
          title: code
          type: string
        term:
          example: Microscopy
          title: term
          type: string
      title: SabCodeTerm
      type: object
    DatasetPropertyInfo:
      description: "Properties of a HuBMAP/SenNet Dataset. Where applicable, key names\
        \ match those found in the original assay_types.yaml."
      example:
        alt-names:
        - MALDI-IMS-pos
        - MALDI-IMS-neg
        dataset_provider: HuBMAP IEC
        data_type: bulk-RNA
        description: Bulk RNA-seq
        vitessce-hints: Microscopy
        vis-only:
        - "true"
        - "true"
        contains-pii: "true"
        primary: "true"
      properties:
        alt-names:
          description: Alternative/deprecated synonyms of data_type that may still
            be associated with dataset entities
          example:
          - MALDI-IMS-pos
          - MALDI-IMS-neg
          items:
            type: string
          title: alt-names
          type: array
        contains-pii:
          description: Whether the dataset contains Patient Identifying Information
            (PII)
          example: "true"
          title: contains-pii
          type: string
        data_type:
          description: Data type for the dataset; used to characterize dataset entities
            in provenance hierarchy
          example: bulk-RNA
          title: data_type
          type: string
        dataset_provider:
          description: Identifies the provider of the dataset. 'External Provider'
            also referred to as 'lab-processed'.
          example: HuBMAP IEC
          title: dataset_provider
          type: string
        description:
          description: How datasets of the data type are named in the Data Portal.
          example: Bulk RNA-seq
          title: description
          type: string
        primary:
          description: Indicates whether the assay is primary (true) or derived (false)
          example: "true"
          title: primary
          type: string
        vis-only:
          description: Indicates whether for visualization only
          items:
            example: "true"
            type: string
          title: vis-only
          type: array
        vitessce-hints:
          description: Flags for Vitessce visualization
          example: Microscopy
          items:
            example: "[\"pyramid\",\"anndata\",\"is_image\",\"is_tiled\",\"is_sc\"\
              ,\"rna\",\"atac\",\"sprm\",\"codex\",\"maldi\"]"
            type: string
          title: vitessce-hints
          type: array
      title: DatasetPropertyInfo
      type: object
    AssayTypePropertyInfo:
      description: Properties of a HuBMAP/SenNet AssayType. 'DatasetPropertyInfo.data_type'
        matches key in original assay_types.yaml.
      example:
        name: bulk-RNA
        description: Bulk RNA-seq
        vitessce-hints:
        - "[\"pyramid\",\"anndata\",\"is_image\",\"is_tiled\",\"is_sc\",\"rna\",\"\
          atac\",\"sprm\",\"codex\",\"maldi\"]"
        - "[\"pyramid\",\"anndata\",\"is_image\",\"is_tiled\",\"is_sc\",\"rna\",\"\
          atac\",\"sprm\",\"codex\",\"maldi\"]"
        vis-only:
        - true
        - true
        primary: true
        contains-pii: true
      properties:
        name:
          description: AssayType name; used to characterize dataset entities in provenance
            hierarchy
          example: bulk-RNA
          title: name
          type: string
        primary:
          description: Indicates whether the assay is primary (true) or derived (false)
          example: true
          title: primary
          type: boolean
        description:
          description: How datasets of the data type are named in the Data Portal.
          example: Bulk RNA-seq
          title: description
          type: string
        vitessce-hints:
          description: Flags for Vitessce visualization
          items:
            example: "[\"pyramid\",\"anndata\",\"is_image\",\"is_tiled\",\"is_sc\"\
              ,\"rna\",\"atac\",\"sprm\",\"codex\",\"maldi\"]"
            type: string
          title: vitessce-hints
          type: array
        contains-pii:
          description: Whether the dataset contains Patient Identifying Information
            (PII) (true or false)
          example: true
          title: contains-pii
          type: boolean
        vis-only:
          description: Indicates whether for visualization only (true or false)
          items:
            example: true
            type: boolean
          title: vis-only
          type: array
      title: AssayTypePropertyInfo
      type: object
